# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0004_auto_20151202_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.PositiveSmallIntegerField()),
                ('tag', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.Game')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_dev', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='payment',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.User'),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.User'),
        ),
        migrations.AddField(
            model_name='game',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.User'),
        ),
    ]
