# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0005_auto_20160226_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='player',
            new_name='buyer',
        ),
    ]
