# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default='Empty', max_length=500),
        ),
    ]
