# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0011_auto_20160312_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tag',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure')], max_length=255),
        ),
    ]
