# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0012_auto_20160313_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tag',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Arcade', 'Arcade'), ('Fighting', 'Fighting'), ('Mini', 'Mini'), ('Puzzle', 'Puzzle'), ('Racing', 'Racing'), ('Shooter', 'Shooter'), ('Sport', 'Sport'), ('Strategy', 'Strategy')], max_length=255),
        ),
    ]
