# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 13:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0013_auto_20160313_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='picture',
            field=models.CharField(default=datetime.datetime(2016, 3, 26, 13, 22, 51, 438034, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
