# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0014_game_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='picture',
            field=models.URLField(),
        ),
    ]
