# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0015_auto_20160326_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='picture',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg'),
        ),
    ]
