# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0018_savedgames'),
        ('webshop', '0018_auto_20160410_0749'),
    ]

    operations = [
    ]
