# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 15:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0019_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedgames',
            name='game',
        ),
        migrations.RemoveField(
            model_name='savedgames',
            name='player',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='success',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('pending', 'pending')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='SavedGames',
        ),
    ]
